version: '3.9'

services:
    mongodb:
      image: mongo:5.0.8
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: senha123
      restart: always

    api:
      build:
        context: .
      ports:
        - 5000:5000
      restart: always
      depends_on:
        - mongodb
      volumes:
        - .:/app
